### PR TITLE
Improve lambdaHandler to cover more use cases

### PR DESCRIPTION
**Pull request by jogold**
Merge strategy: `merge`

### CODE REVIEW

**Comment by jogold** [comment]
image

**Comment by jogold** [comment]
I think we should also add `shouldLogResponse` and `transformLogResponse` (log of handler response). What do we want as default here?

**Comment by dalawwa** [comment]
> I think we should also add `shouldLogResponse` and `transformLogResponse` (log of handler response). What do we want as default here?

In my opinion, ``true`` as default for `shouldLogResponse`'s and ``false`` as default for `transformLogResponse`.

**Comment by jogold** [comment]
image

**Comment by jogold** [comment]
@goldwasserexchange/developers ok with this version?

**Pull request merged**
