### PR TITLE
feat(eslint-config-typescript): update and use recommended rules

### PR DESCRIPTION
**Pull request by belgac**

### CODE REVIEW

**Comment by jogold** [comment]
Linting fails?

**Comment by belgac** [comment]
> Linting fails?

i'm looking into it

**Comment by jogold** [comment]
We should also update to latest version in this PR (2.24.0 for plugin and parser).

**Comment by dalawwa** [comment]
Looks good to me

**Comment by jogold** [comment]
I think that we also need to configure the rule https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/extensions.md correctly in `eslint-config-import`.

**Comment by jogold** [comment]
The default here will not be OK https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/imports.js#L139

**Comment by belgac** [comment]
> I think that we also need to configure the rule [benmosher/eslint-plugin-import:docs/rules/extensions.md@`master`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/extensions.md) [](/benmosher/eslint-plugin-import/blob/HEAD@{2020-03-20T09:46:14Z}/docs/rules/extensions.md) correctly in `eslint-config-import`.

I don't get what i misconfigured? https://github.com/goldwasserexchange/public/pull/245/files#diff-533bfb4d23c92a47b738096abdf71e75R25

**Comment by jogold** [comment]
There's the `settings > import/extensions` but also the `rules > import/extensions`. The later specifies when to force or omit extensions in imports.

**Comment by jogold** [comment]
https://github.com/benmosher/eslint-plugin-import#importextensions VS https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/extensions.md

**Pull request merged**
